"""Build the report only from verified offline outputs, with HLS gaps explicit."""
import csv,json
from pathlib import Path
ROOT=Path(__file__).resolve().parents[2]
out=ROOT/'layer_validation/results'
s=json.loads((out/'offline_summary.json').read_text())
full=json.loads((out/'python_mixed_full10000.json').read_text())
with (out/'layer_float_fixed_error.csv').open() as f: rows=list(csv.DictReader(f))
lines=['# 逐层参考模型、故障定位与混合精度离线确认','','## 状态与课程要求','','本模块对应任务书的分层比对及故障定位要求，目前完成离线参考模型验证和定位器自检；HLS中间特征图导出脚本已准备，但未运行成功。此前HLS安装在E盘，本次系统未挂载E盘，启动失败原始日志保存在hls_unavailable/run.log。不能将本模块写成已完成硬件逐层验证。','','## 独立定点模型','','Python使用整数运算实现AP_RND（中点向正无穷舍入）和AP_SAT。激活/参数为16位、6位整数、10位小数；累加器32位、14位整数、18位小数。每次乘积先舍入到累加精度，每次加法都执行饱和；累加次序与模型前向顺序一致。没有以普通numpy浮点点积冒充定点仿真。边界单元测试覆盖负数中点舍入、累加饱和以及不完整/重复轨迹拒绝。','','独立Python模型与仓库已经完成的逐行缓存HLS输出比较：1000张、10000个logits全部逐位一致，正确982张。这里复用了已有HLS证据，没有重新运行HLS。相同输入blob哈希在脚本中强制核验。','','## 分层分析','','每类取原MNIST测试集最先出现的两张，共20张；原始索引保存于offline_summary.json。导出Conv1(ReLU后)、Pool1、Conv2(ReLU后)、Pool2、FC1(ReLU后)、FC2(ReLU后)和logits。以下误差是Python浮点与Python定点的差异，不是实测HLS层误差：','','|层|元素数|平均绝对误差|最大绝对误差|输出恰在定点上下限数|','|---|---:|---:|---:|---:|']
for r in rows: lines.append('|'+ '|'.join([r['layer'],r['values'],r['mean_absolute_error'],r['max_absolute_error'],r['output_at_limit']])+'|')
lines+=['','输出恰在上下限的数量不是逐MAC累加溢出计数，不能据此推断中间累加永不饱和。','','## 故障定位自检','','故意将Python Pool1的[0,0,0]增加1.0（原始整数1024），然后继续计算后续层。20张全部定位到Pool1索引0，Conv1保持一致。该实验是明确标记的Python合成故障；它证明轨迹比较器可以找到最早分歧，不是HLS故障注入已经通过。比较器对缺层、缺元素、重复坐标会直接报错，防止不完整输出被当成通过。','','## 混合精度完整集离线结果','',f"权重Q8.1、激活/bias Q16.6的Python整数参考在10000张上正确{full['correct']}张，准确率{full['accuracy_percent']:.2f}%。先检查前1000张的全部logits与已有混合精度HLS结果逐位一致，再扩展到10000张。",'','这补充了候选的完整集Python证据；其余9000张尚无本次HLS验证。它不替换同学原有完整HLS结果，不据此标记full_hls_status为完成。逐样本输出为python_mixed_full10000.csv，文件名和JSON均注明Python。','','## 恢复HLS后的步骤','','1. 恢复原E盘或通过--hls-root指定实际安装目录，运行tools/run.py。','2. 运行tools/check_hls.py，对真实clean/fault轨迹进行结构检查和逐位比较；只有两组实际HLS日志和轨迹都通过才写出hls_layer_verification.json。','3. 插桩与故障均位于#ifndef __SYNTHESIS__内部，未修改已验证row_cache源码。本次未重新综合，不能报告新的资源或时序。','','## 证据','','- golden_vs_existing_hls.csv：1000张离线/已有HLS对照。','- python_reference_trace.csv.gz、python_fault_trace.csv.gz：20张Python中间轨迹。','- fault_localization.json：20张首次错误位置。','- layer_float_fixed_error.csv与layer_diagnostics.png：Python层误差及特征图。','- python_mixed_full10000.csv/JSON：混合精度完整集Python参考结果。','- hls_unavailable/run.log：未能运行HLS的实际失败记录。','','## 仍需团队完成','','真实自采图像和背景负样本、Level 2正式评估；HLS恢复后的逐层验证及候选完整集验证；UNROLL并行度/资源容量边界；各成员报告章节和答辩。原任务书不要求上板。']
(out/'experiment_report.md').write_text('\n'.join(lines)+'\n',encoding='utf-8')
